steps:
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['build']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/spring-boot', '.']
  
  - name: gcr.io/cloud-builders/gcloud
    args: [app, deploy]
